(Nr. in short section) & Grundlagen & Basic conversatie & بنیادی بات چیت &  &  &  &  \\ 
000 & Hallo & Hallo & سلام & hello/salam & سلام & Salaam &  سلام \\ 
001 & guten Morgen & Goedendag & صبح بخیر & shubho din / suprobhat | slāmālikum & صبح بخیر & Sob bekhair & سهار په خیر \\ 
002 & guten Abend & Goedenavond & شب بخیر & shubho sandhyā & شب بخیر & Shaw bekhair & شپه په خیر \\ 
003 & auf Wiedersehen & Tot ziens /  & خدا حافظ /  & abar dekha hobe & خداحافظ & khodaafez & د خدای په امان    \\ 
004 & Entschuldigung & Pardon & معاف کیجیے /  & maf korben..  & بيبخشين & Bebakhshin & وبښه  \\ 
005 & bitte & Alstublieft (aub) & مہربانی & please/ doya kore & لطفاً & Lutfan & لطفاً/مهربانی \\ 
006 & danke & Dank u; dank je; bedankt & شکریہ /  & dhonnobad & تشكر & Tashakor & مننه  \\ 
007 & gern geschehen & Graag gedaan &  &  &  &  &  \\ 
008 & Ich heiße... & Mijn naam is ... & میرا نام...ہے & amar nam ... & نام ام ..... است & Naamam ...ast & زما نوم ... دی  \\ 
009 & Wie heißen Sie? & Hoe heet u? & آپ کا نام کیا ہے؟ /  & apnar nam ki? & نام تان چیست؟ & Naametaan chist? & ستاسو څه نوم دی؟   \\ 
010 & Ich komme aus... & Ik kom uit ... & میں ۔۔۔۔۔۔۔۔ سے آئی ہوں  /  / میں ۔۔۔۔۔۔۔۔ سے آیا ہوں /  & ami .... theke ashchhi & (مں از ۔۔۔۔۔۔۔۔ می آیم & Man az .... mi aayum & زه د ... یم  \\ 
011 & (die) Familie & (de) familie & خاندان & poribar & فامل & Faamil &  \\ 
012 & (Das ist mein) Mann & Dit is mijn man & یہ میرا شوہر ہے & uni ... amar shami & این شوهرم است & Een shoharam ast & دا زما میړه دی  \\ 
013 & (meine) Frau & Mijn vrouw &  میری بیوی  & amar stri  &  / همسرم & Hamsaram & زما ښځه  \\ 
014 & (meine) Kinder & mijn kinderen &  میرے بچّے  /  & amar bachchara & اولادهایم & Awladaayam & زما ماشومان  \\ 
015 & (meine) Tochter & mijn dochter &  میری بیٹی & amar meye & دخترم & dokhtaram & زما لور /  \\ 
016 & (mein) Sohn & mijn zoon &  میرا بیٹا  & amar chhele &  بچیم & bachim & زما ځوی  \\ 
017 & (mein) Baby & mijn baby &  میرا  بچہ & amar bachcha & نوزادم & nozaadam & زما وړوکی  \\ 
018 & (Das ist mein) Bruder. & Dit is mijn broer. & یہ میرا بھائی ہے & eta ... amar bhai & این برادرم است. & In baraadaram ast. & دا زما ورور دی     \\ 
019 & (Das ist meine) Schwester. & Dit is mijn zus. & یہ میری بہن ہے & eta ... amar bon & این خواهرم است. & In khwaaram ast. & دا زما خور ده   \\ 
020 & (Das ist mein) Vater / Papa & Dit is mijn vader. & یہ میرے باپ/ والد/ ابو ہیں & eta ... amar baba & این پدرم (بابام) است. & In padaram/babam ast. & دا زما پلار دی    \\ 
021 & (Das ist meine) Mutter / Mutti / Mama & Dit is mijn moeder. & یہ میری والدہ/ امّی ہیں۔ & eta ... amar maa & این مادرم است. & In maadaram ast. & دا زما مور ده     \\ 
022 & Ich habe Hunger. & Ik heb honger. & مجھے بھوک لگی ہے /  & amar khide legechhe / ami khudharto / ami kichhu khete chai & گشنه هستم & goshna hastum & زه وږی يم  \\ 
023 & (mein Kind) hat Hunger & (Mijn kind) heeft honger. & میری بچّی بھوکی ہے۔ /  /   / میرا بچّا بھوکا ہے۔ & amar bachchatar khide legechhe & بچه ام گشنه شد. & bachem goshna shod. & (زما بچه) وږی دی  /  \\ 
024 & Ich habe Durst. & Ik heb dorst. & مجھے پیاس لگی ہے۔ /  & amar pipasha legechhe / ami pani khabo & تشنه استم. & Toshna astam. & زه تږی يم    \\ 
028 & Wasser & (het) water & پانی & pani & آب  & aaw &  \\ 
029 & Haben Sie... & Heeft u... & کیا آپ کے پاس ۔۔۔۔ ہے؟ /  & apnar kachhe ki .... achhe? & ....دارین؟ & ...daarin? & ... لرې؟      \\ 
030 & Wo ist... & Waar is ... & ۔۔۔۔ کہاں ہے؟ & ... kothay? & ...کجاست؟ & ...kojaast? & ... چېرته دی؟        \\ 
031 & Wo ist die Toilette?  / / Wo ist das Badezimmer? & Waar is de wc / Waar is de badkamer? & غسل خانہ کدھر ہے؟ /  & bathroom ta kothay? &  تشناب کجاست؟ & Tashnaab kojast? & تشناب / غسل خانه چېرته دی؟    \\ 
032 & Ich brauche eine Dusche & Ik moet/wil douchen. & مجھے نہانے کی ضرورت ہے۔ /  & amake goshol korte hobe & باید شاور بی گیرم. & Baayad shaawar bigiram. & زه غواړم غسل وکړم       \\ 
033 & Wo kann ich duschen? & Waar kan ik douchen? & میں کہاں نہا سکتی/ سکتا ہوں؟ & ami kothay goshol korte pari?  & در کجا شاور بی گیرم؟ & Da kojaa shaawar bigiram? & چیرته کولای شم غسل وکړم؟     \\ 
034 & (die) Damenbinde & (het) maandverband & سینیٹری پیڈ / تولیہ / کپڑے & sanitary pad & نوار بهداشتی & nawaree bedashati & توکري       \\ 
035 & (die) Windel & (de) luier; (het) verband & لنگوٹ / ڈایپر & daipar & پوشک & pooshak & اوړني \\ 
036 & Ich muss anrufen / telefonieren & Ik moet telefoneren. & مجھے فون کرنا ہے۔ & amake ekta fon korte hobe & باید تلفن کنم (زنگ بزنم) & baayad telefun konam/zang bezanam & زه غواړم تیلفون وکړم.      \\ 
037 & Wo kann ich beten? & Waar kan ik bidden? & میں کہاں نماز پڑھ سکتی/سکتا ہوں؟ & ami kothay namaj porte pari? & کجا نماز خوانده می توانم؟ & Kojaa namaaz khaandah metaanam? & چیرته کولای شم لمونځ وکړم؟      \\ 
 & Wo kann ich ..... kaufen? & Waar kan ik ..... kopen? & میں کہاں ۔۔۔۔ خرید سکتی/سکتا ہوں؟ & .... kothay kinte pawa jay  & ــــــــ از کجا بخرم؟ & ..... az koja bekharam? & چیرته ... پیرودلی/اخیستلی شم؟ \\ 
038 & Wo kann ich ..... finden? & Waar kan ik ..... vinden? & ۔۔۔۔۔ کہاں ملےگا / ملےگی؟ & ... kothay pabo? & ــــــــ کجا پیدا کنم؟ & ..... koja payda konam? & چیرته ... موندلای/پیدا کولای شم؟ \\ 
039 & Wie spät ist es? & Hoe laat is het? & کتنا بجا ہے؟ & kota baje & چند بجا است؟ & Chand bajaa ast? & څو بجې دي؟ \\ 
040 & Ich muss schlafen / Wir müssen schlafen & Ik moet slapen / Wij moeten slapen. & مجھے(ہمیں) سونا ہے & amake ghumate hobe & باید خواب کنم / کنیم. & Baayad khaaw konam/konim. & مونږ باید بیده شو    \\ 
041 & Wo ist die U-Bahn? & Waar is de metro? /  & مٹرو/سب وے/او۔بان کہاں ہے؟ & U-Bahn kondike? & مترو کجاست؟ & metro kojaast? & د اورګاډي ایستګاه چیرته ده؟   \\ 
 & Ich habe kein Geld. & Ik heb geen geld. & میرے پاس پیسے نہیں ہیں۔ & amar kachhe kono taka nei & پیسه ندارم. & paysah nadaaram. & ما سره پيسې نشته    \\ 
042 & Sprechen Sie…? & Spreekt u ...? & کیا آپ ۔۔۔ بولتے/بولتی ہیں؟ & apni ki .... bolte paren? & ... گپ می زنی؟ & ... gap mezani? & ... ژبه درځي؟          \\ 
043 & Ich spreche nicht so gut (Deutsch). & Ik spreek (niet zo goed) Nederlands. & میری جرمن/انگریزی بہت اچھی نہیں ہے۔ /  & ami khub ekta bhalo (German) bolte parina & المانیم خوب نیست /  & almaaniyam khub nist & ما ته الماني ژبه (ښه) نه راځي    \\ 
044 & Können Sie das für mich aufschreiben ? & Kunt u dat voor me opschrijven? &  یہ  آپ لکھ سکتے ہیں ? /  & apni ki amake ektu likhe dite parben? & برایم او را نویشته کرده می توانی؟ & baraayem oo ra newishta karda metaani? & ما ته دا وليکئ ؟         \\ 
045 & Ich verstehe das nicht. & Ik begrijp het niet & مجھے سمجھ  نہیں آیا /  & ami bujhte parchhi na & نمی فهمم & namifahmam & زه نه پوهېږم       \\ 
 & Hilfe! / Bitte helfen Sie mir ! & Help! / Help me alstublieft! & بچاو! /میری مدد کیجیئے /  & ba(n)chao! amake doya kore ektu shahajjo korun &  کمک ! & Komak! &  \\ 
046 & Ich weiß nicht & Ik weet het niet. & مجھے نہیں معلوم & ami jani na & نمی دانم & namedaanam & نه پوهېږم     \\ 
047 & Was ist passiert? & Wat is er gebeurd? & کیا ہوا؟ /  & ki hoyechhe & چی شد؟ & Chi shod? & څه شو؟      \\ 
048 & Mir ist kalt. / Ich friere. & Ik bevries / heb het koud. & مجھے بہت سردی لگ رہی ہے۔  /  & amar sheet lagchhe & خنک می خرم. & khonuk mekhurum & زما یخ/ساړه کیږي     \\ 
049 & 😊 Ich freue mich / ich bin glücklich & Ik ben blij/gelukkig. & میں خوش ہوں۔ & amar khushi lagchhe / ami khushi & خوش شدم. & Khush shodam. & زه خوشحاله يم    \\ 
050 & 😰 Ich habe Angst & Ik ben bang. & مجھے ڈر لگ رہا ہے۔ /  & amar bhoy korchhe & می ترسم & metarsam & يېرېږم     /  \\ 
051 & 😢 Ich bin traurig. & Ik ben verdrietig. & میں  اداس ہوں & amar mon kharap & غمگین شدم. & Ghamgin shodam. & زه خپه یم     \\ 
052 & 😍 Ich mag dich. & Ik vind je aardig. 😊 / Ik vind je lief. 😍 & تم مجھے پسند ہو۔ & amar tomake pochhondo & شما را دوست دارم. & shoma ra dost daaram. & ته زما خوښ يې     \\ 
053 & keine Sorge & Maak je geen zorgen. & فکر نا کریں & chintar kichhu nei  & فکر نکنین. & Fekar nakonin. & تشویش مه کوه    \\ 
054 & Ich hätte gerne einen Termin. & Ik will graag een afspraak maken. & مجھے اپائینڈمنٹ/ملاقات کا وقت چاہیئے۔ & amar appointment lagbe & میخوام یک قرار بگیرم & Mekhaayam yak qaraar bigiram. & زه د ملاقات وخت غواړم \\ 
055 & Wo ist das Zimmer Nummer ...? & Waar is kamer nummer..? & کمرہ نمبر.... کہاں ہے۔ & room number ... ta kondike? & اتاق نمبر ـــــــ کجاست؟ & Otaaq nambare .... kojast? & کوټه/خونه شمیره ... چیرته ده؟ \\ 
056 & Wo ist die Erstaufnahmestelle? & Waar is het registratiekantoor? & رجسٹریشن سنٹر کہاں ہے؟ & Registration center ta kothay? & مرکز ثبت کجاست؟ & Markaze sabt kojast? & د ثبت کوټه/خونه چیرته ده؟ \\ 
057 & Sie müssen warten & Je moet wachten / jullie moeten wachten. & آپ کو انتظار کرنا پڑے گا۔ & apnake / tomake ektu opekkha korte hobe & باید صبر کنین. & baayad sabr konin. & باید منتطر شې      \\ 
058 & Wie lange müssen wir hier warten? & Hoe lang moeten we hier wachten? & ہمیں یہاں اور کتنی دیر انتظار کرنا ہو گا؟ & amader ekhane kotokkhon opekkha korte hobe & برای چه مدّت باید اینجا بمانیم؟ /  /  & Baraye chi moddat baayad injaa bemaanim? & څومره انتظار باید وباسو      \\ 
059 & ein Tag & een dag & ایک دن & ek din & یک روز & yak roz & یوه ورځ      \\ 
060 & eine Stunde & een uur & ایک گھنٹہ & ek ghonta & یک ساعت & yek saa’at & یو ساعت    \\ 
061 & ein Monat & een maand & ایک مہینہ &  &  &  &  \\ 
062 & sehr bald & binnenkort; heel snel & بہت جلد & khub shighri & به زود & ba zood & ډیر ژر     \\ 
063 & morgen & morgen & کل & agami kal & فردا & fardaa &  \\ 
064 & übermorgen & overmorgen & پرسوں & agami porshu & دو روز بعد & du roz baad &  \\ 
065 & nächste Woche & volgende week & اگلے ہفتے & porer shoptahe &  هفته دیگه  & haftaye digaa &  \\ 
066 & Ich komme bald zurück & Ik kom snel terug. & میں جلدی واپس آونگا & ami khub taratari fire ashbo & زود پس می آیم. & zood pas miyaayam. & زه ژر بیرته راځم    \\ 
067 & 1 eins, 2 zwei, 3 drei, 4 vier 5 fünf, 6 sechs, 7 sieben, 8 acht, 9 neun, 10 zehn & een, twee, drie, vier, vijf, zes, zeven, acht, negen, tien /  & ایک، دو، تین، چار، پانچ، چھ، سات، آٹھ، نو، دس & ek, dui, tin, char, pa(n)ch, chhoy, sat, aat, noy, dosh & یک،دو،سه،چهار،پنج،شش،هفت،هشت،نه،ده & yak, du, seh, chaar, panj, shash, haft, hasht, noh, dah & یو، دوه، درې، څلور، پنځه، شپږ، اووه، اته، نه، لس     \\ 
068 & Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag & maandag, dinsdag, woensdag, donderdag, vrijdag, zaterdag, zondag & سوموار، منگل، بدھ، جمعرات، جمعہ، ہفتہ، اتوار &  & یکشنبه. دوشنبه. سه شنبه. چهارشنبه. پنج شنبه. جمعه. روز شنبه & Yak-shanbe, Du-shanbe, Seh-shanbe, Chaar-shanbe, Panj-shanbe, Juma, Rooz-e-shanbe &  \\ 
069 & Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember & januari, februari, maart, april, mei, juni, juli, augustus, september, oktober, november, december & جنوری، فروری، مارچ، اپریل، مئی، جون، جولائی، اگست، ستمبر، اکتوبر، نومبر، دسمبر &  &  &  &  \\ 
070 &  &  &  &  &  &  &  \\ 
071 & Gesundheit & Gezondheid / Medische Termen & طبی الفاظ &  &  &  &  \\ 
072 & Ich brauche einen Arzt. & Ik heb een dokter nodig. & مجھے ڈاکٹر کی ضرورت ہے۔ /  & amake daktarer kachhe jete hobe & دکتر ضرورت دارم & Doctor zaroorat daaram. & طبيب مي په کار دی   /  \\ 
073 & Mir ist schlecht. & Ik ben misselijk. & میری طبعیت ٹھیک نہیں ہے & amar bomi pachchhe & نجور هستم. & Najor astam. &  \\ 
74 & Ich bin krank. & Ik ben ziek. & میں بیمار ہوں۔ /  & ami osustho / amar shorir kharap & مریض شدم & mariz shodam & زه ناجوړ يم  \\ 
75 & (mein Kind) ist krank & (Mijn kind) is ziek. &   میرا بچہ بیمار ہے & amar bachchatar oshukh & بچه ام مریض شد. & bachem mariz shod. & (زما بچه) ناجوړ دی  /  \\ 
 & Ich bin schwanger & Ik ben zwanger. & میں حاملہ ہوں & ami gorbhoboti & من حامله دار استم. & Ma haamela daar astam. & زه بلربه یم/حمل لرم       \\ 
076 & Ich habe eine allergische Reaktion & Ik heb een allergische reactie. & مجھے اس کی وجہ سے الرجی ہو رہی ہے &  &  &  &  \\ 
077 & Mir ist schwindelig. & Ik ben duizelig. & مجہے چکر آ  رہے ہیں & amar matha ghurchhe & من  سر چرخا هستم & Man zar charkha hastam.  &  \\ 
 & Ich leide an Diabetes & Ik heb diabetes. & میں ذیابیطس ہوں &  &  &  &  \\ 
078 & Ich brauche Insulin & Ik heb insuline nodig.  & مجھے انسولین چاھیے &  &  &  &  \\ 
079 & Ich wurde vergewaltigt. & Ik ben verkracht. & میری عزت لوتی گئی & amake dhorshon kora hoyechhe & من تجاوز شدم. & Ma tajaawoz shodam. &  \\ 
080 & Ich habe Bauchschmerzen. & Ik heb buikpijn. /  & میرے پیٹ میں درد ہے۔ & amar pet betha korchhe & معده ام درد می کند. & Medam dard mekona. & خېټه مې خوږېږي     \\ 
081 & Ich habe Fieber & Ik heb koorts. & مجھے بخار ہے۔ & amar jor & تب دارم. & Tab daram. & زما تبه ده    \\ 
082 & Ich habe Kopfschmerzen. & Ik heb hoofdpijn. & میرے سر میں درد ہے۔ & amar matha dhorechhe & سرم درد می کند. & Saram dard mekona. & سر مې خوږيږي    \\ 
083 & Ich habe Husten. & Ik moet hoesten. & مجھے کھانسی ہے۔ & amar kashi hoyechhe & سرفه می کنم  & Sorfa mekonam. & زه ټوخیږم    \\ 
084 & Ich habe Halsschmerzen. & Ik heb keelpijn. & میرا گلہ خراب ہے & amar gola betha korchhe &  گلون ام درد می کند.  & Glunam dard mekona. & زما ستونی خوږیږي     \\ 
085 & Mein Kind hat Halsschmerzen/Husten. & Mijn kind moet hoesten. & میرے بچے کو کھانسی  ہے۔ & amar bachchare kashi hoyechhe & بجه ام سرفه می کند / گلون اش درد می کند. & Bachem sorfa mekona / glunesh dard mekona. & زما بچی/بچۍ ټوخیږي \\ 
086 & (die) Erkältung & Verkouden; (de) verkoudheid & زکام & thanda laga & ریزش & rezesh & ریزش/زکام \\ 
087 & (der) Durchfall & diarree & دست  & dayriya/amasha &  اسهال  & eshaal & نس ناستی/اسهال \\ 
 & (die) Verstopfung & verstopping & قبض & kosha & قبض & qabz & قبضیت \\ 
 & (der) Scheidenpilz & vaginale schimmel &  خمیر انفکشن & vaginal yeast infection (thrush) &  &  &  \\ 
088 & (der) Fußpilz & voetschimmel & کھلاڑی کے پاؤں کا انفکشن & Payer fungal infection &  &  &  \\ 
 & (die) Läuse / (die) Kopfläuse & hoofdluis & سر کی جویں & ukun &  &  & سپږي \\ 
 & Lebensmittel & Eten & کھانا & khabardabar  & غذا  & Ghazaa &  \\ 
 & (das) Frühstück & ontbijt & ناشتا &  &  &  &  \\ 
89 & (das) Mittagessen & lunch & دوپہر کا کهانا &  &  &  &  \\ 
91 & (das) Abendessen & avondeten & رات کا کهانا &  &  &  &  \\ 
 & Ist das Essen Halal? & Is het eten halal? & کیا یہ کھانا حلال ہے؟ & khabarta ki halal  & این غذا حلال است؟ & in ghazaa halaal ast? & ډوډۍ حلال دی؟  \\ 
92 & Ich bin allergisch gegen… & Ik ben allergisch voor ... & مجھے ۔۔۔ سے الرجی ہے۔ & amar ... te allergy achhe  & به...آلرژی دارم & Ba .... allerji daaram. & زه حساسیت لرم له...       \\ 
93 & (das) Rindfleisch & (het) rundvlees & گائےکاگوشت & gorur mangsho &  گوشت گاو & Goshte gaaw &  \\ 
94 & (das) Huhn & kip & مرغی & murgi & مرغ & Morgh &  \\ 
95 & Ich esse kein Schweinefleisch & Ik eet geen varkensvlees & میں سور کا گوشت نہیں کھاتا & ami shukorer mangsho khaina  & من گوشت خوک نمیخورم & Ma goshte khok namekhoram. &  \\ 
96 & Ich bin Vegetarier. Ich esse kein Fleisch und keinen Fisch. & Ik ben vegetariër. Ik eet geen vlees en vis. & میں صرف سبزی کھاتا ہوں. مجھے گوشت یا مچھلی نہیں چاہیے & ami kono machh-mangsho khai na &  گوشت و ماهی نمیخورم & Gosht wa maahi namekhoram. & زه غوښه نخورم    \\ 
97 & (die) Eier [pl] & (de) eieren & انڈے & dim & تخم مرغ  /  & Tokhome morgh &  \\ 
 & (der) Fisch & (de) vis & مچھلی & machh & ماهی & Maahi &  \\ 
 & (das) Brot & (het) brood &  روٹی & ruti & نان خشک & Naane khoshk & وچه ډوډۍ     \\ 
98 & (das) Wasser & (het) water & پانی & pani & آب & aaw & اوبه     \\ 
99 & (die) Milch & (de) melk & دودھ & dudh &  شیر & shir & شوده    \\ 
 & (der) Kaffee & (de) koffie & کوفی & Kofi & کوفی / قهوه & Kofi / qahwa &  \\ 
100 & (der) Tee & (de) thee & چائے & cha & چای & Chai &  \\ 
101 & Ich trinke keinen Alkohol & Ik drink geen alcohol & میں شراب نہیں پیتا & ami mod/alcohol khaina & من الکل نمیخورم  & Ma alkol namekhoram &  \\ 
102 & (das) Obst & (het) fruit & پھل & Pfol & میوه  & mewa &  \\ 
102 & (der) Apfel & (de) appel & سیب & Apel &  سیب & sib &  \\ 
104 & (die) Orange/Apfelsine & (de) sinaasappel & سنترہ / مالٹا & Komola & نارنج & naaranj &  \\ 
 & (der) Pfirsich & (de) perzik & آڑو & Peach & شفت آلو & shaftaalu &  \\ 
105 & (die) Gemüse [pl] & (de) groente & سبزیاں & Shobji &  سبزیجات & sabzijaat &  \\ 
 & (die) Kartoffeln [pl] & (de) aardappelen; (de) aardappels & آلو & alu & کج آلو & Kachaalu &  \\ 
106 & (die) Bohnen [pl] & (de) bonen & لوبیا & borboti /sim & لوبیا  & loobiaa &  \\ 
107 & (die) Erbsen [pl] & (de) erwten & مٹر & Motorshuti &  نخود & nokhod &  \\ 
108 & (die) Kichererbsen [pl] & (de) kikkererwten & چھولا / چنے &  & شور نخود & shor nakhot &  \\ 
 & (die) Aubergine & (de) aubergine & بینگن &  & باذنجان سیاه & banjaan siyaah &  \\ 
109 & (die) Karotten/Möhren [pl] & (de) wortelen; (de) wortels & گاجر & Gajor & زردک & zardak &  \\ 
110 & (die) Tomaten [pl] & (de) tomaten & ٹماٹر & Tomato  & باذنجان رومی & banjaan-e-rumi &  \\ 
111 & (der) Zucker & (de) suiker & شکر & chini & شکر & shakar &  \\ 
112 & (das) Mehl & (de) bloem & آٹا & Ata /moyda & آرد  & aard &  \\ 
113 & (der) Honig & (de) honing & شہد & modhu & عسل & asal &  \\ 
114 & (der) Käse & (de) kaas & پنیر / چیز & Ponir &  پنیر & panir &  \\ 
115 & (das) Salz & (het) zout & نمک & lobon &  نمک  & namak &  \\ 
116 & (der) Pfeffer & (de) peper & گول مرچ & golmorich & مرچ سرخ & murch-e-sorkh &  \\ 
 & (der) Reis & (de) rijst & چانول & chal / bhat & برنج  & brinj &  \\ 
 & (die) Nudeln & (de) pasta & پاستہ / نوڈل & Noodle &  ماکارونی & maakaaroni &  \\ 
117 & (die) Suppe & (de) soep & سوپ & sup & آش  & aash &  \\ 
118 & (die) Butter & (de) boter & مکّھن & makhon &  & maska &  \\ 
119 & (das) Öl & (de) olie & تیل & tel & تیل & teyl &  \\ 
 & (die) Gabel & (de) vork & کانٹا & ka(n)Tachamoch & پنجا & panjaa &  \\ 
 & (der) Löffel & (de) lepel & چمچا & tebil chamoch/ cha chamoch & قاشق / چمچه & qaashoq / chamcha &  \\ 
 & (das) Messer & (het) mes & چاقو & chhuri/chaku & کارد & kaard &  \\ 
120 & (der) Teller & (het) bord & پلیٹ & thala & بشقاب & beshqaab &  \\ 
 & (das) Trinkglas / Glas & (het) glas & گلاس & glas & گیلاس & gilaas &  \\ 
121 & (die) Teekanne & (de) theepot & چائے دانی & chayer ketli & چاینک & chaainak &  \\ 
 &  &  &  &  &  &  &  \\ 
 & Kleidung & Kleding & کپڑے & jamakapor &  لباس  & Lebaas &  \\ 
122 & (das) Hemd & (het) hemd & قمیض & shirt / jama &  بلوز  & bolooz & کمیس      \\ 
123 & (das) Kleid & (de) jurk & لباس/کپڑے &  Jama & لباس & lebaas & کالي      \\ 
124 & (der) Rock & (de) rok & اسکرٹ & skirt  &  دامن  & daaman &  \\ 
125 & (die) Hose & (de) broek & پینٹ / پتلون & pant & پتلون & patloon & پتلون/پرتوګ      \\ 
126 & (der) Pullover & (de) trui & سویٹر & suyetar & جمپر & jampar &  \\ 
128 & (die) Jacke & (de) jas & جیکٹ & jaket & ژاکت & jaakat &  \\ 
129 & (der) Schleier / (das) Kopftuch & (de) sluier / (de) hoofddoek; (de) hijab & حجاب / ڈپٹا / نقاب & hijab/orna & حجاب & hejaab & ټیکری/توکری     \\ 
130 & (die) Schuhe [pl] & (de) schoenen & جوتے & juta & بوت / کفش & boot / kafsh &  \\ 
 & (die) Handschuhe [pl] & (de) handschoenen & دستانے/گلوز & hatmoja & دستکش  & distkash &  \\ 
 & (die) Socken [pl] & (de) sokken & موزے & moja & جوراب & joraab &  \\ 
 & (die) Unterwäsche & (het) ondergoed & انڈر ویئر / جانگھیا / /اندرونی کپڑے & ontorbash & زیر جامه & zirjaamah & نیکر    \\ 
 & Sonstiges & Overig & اور چیزیں & onnanno & مختلف & Mokhtalef &  \\ 
 &  &  &  &  &  &  &  \\ 
 & (das) Bett & (het) bed & بستر / پلنگ & bichhana & چهارپایی & chaar paayi &  \\ 
131 & (die) Decke & (de) deken & کمبل & kombol & کمپل & kampal &  \\ 
132 & (die) Lampe & (de) lamp & لامپ & bati & لامپ & laamp &  \\ 
133 & (das) Telefon & (de) telefoon & ٹیلی فون & telifon & تلفن & talefun & تیلفون    \\ 
134 & (das) Handy & (de) mobiele telefoon; (het) mobieltje & موبائیل فون & muthofon/mobail telifon/selfon & مبایل & mobaayl &  \\ 
 & (die) Elektrizität / (der) Strom & (de) elektriciteit; (de) stroom & بجلی & biddut/karent & برق  & barq &  \\ 
 & (der) Computer & (de) computer & کمپیوٹر & kompiutar & کامپیوتر  & compyutar &  \\ 
135 & (die) Internetverbindung & (de) internetverbinding & انٹرنٹ کنکشن & intarnet shongjog & انترنت & internet &  \\ 
 & (die) Batterie & (de) batterij & باٹری & batari & باطری & baattry &  \\ 
136 & (das) Zimmer & (de) kamer & کمرہ & ghori & اتاق  & otaaq &  \\ 
 & (der) Stuhl & (de) stoel & کرسی & cheyar & چوکی & chawki &  \\ 
 & (der) Tisch & (de) tafel & میز & tebil & میز & meyz &  \\ 
137 & (die) Toilette / (das) WC & (de) WC & غصل خانہ / ٹویلٹ & bathrum/toilet & تشناب & tashnaab &  \\ 
 & (das) Toilettenpapier & (het) toiletpapier & ٹویلٹ کا کاغز & toilet tishu & کاغذ تشناب & kaaghaz-e-tashnaab &  \\ 
138 & (die) Zahnbürste & (de) tandenborstel & دانت مانجھنے کا برش & da(n)ter brash & مسواک  & maswaak &  \\ 
140 & (die) Zahnpasta & (de) tandpasta & ٹوتھ پہسٹ / دنت منجن & tuthpest & خمیردندان & khamir dandon &  \\ 
141 & (die) Dusche & (de) douche & شاور & shawar/goshol  & شاور & shaawar &  \\ 
 & (die) Badewanne & (het) bad & ٹب & bathtab & جان شوی & jaan shoy &  \\ 
 & (die) Seife & (de) zeep & صابن & shaban & صابون  & saaboon &  \\ 
142 & (das) Shampoo & (de) shampoo & شامپو & shampu & شامپو & shaampoo &  \\ 
143 & (das) Taschentuch & (de) zakdoekjes & رومال & tishu/rumal & دستمال & dastmaal &  \\ 
144 & (der) Schrank & (de) kast & الماری / کابینٹ & almari & کمد & komod &  \\ 
145 & (die) Tür & (de) deur & دروازہ & dorja & دروازه & darwaaza &  \\ 
146 & (das) Fenster & (het) raam & کهڑکی & janala & پنجره & panjara &  \\ 
 & (die) Wand & (de) muur & دیوار & deyal & دیوار & deewaar &  \\ 
 & (das) Haus & (het) huis & مکان & bari & خانه & khaanah &  \\ 
 & (die) Wohnung & (de) woning & فلیٹ & basha & آپارتمان & Apaartemaan &  \\ 
 & (das) Buch & (het) boek & کتاب & boi & کتاب & kitaab &  \\ 
 & (die) Zeitung & (de) krant & اخبار & khoborer kagoj & روزنامه & roznaamah &  \\ 
 & (das) Radio & (de) radio & ریڈیو & betar & رادیو & radio &  \\ 
147 & (das) Fernsehen & (de) televisie & ٹیلی ویژن & telibhishon & تلویزیون & talwiziyun &  \\ 
148 &  &  &  &  &  &  &  \\ 
150 &  &  &  &  &  &  &  \\ 
151 &  &  &  &  &  &  &  \\ 
152 &  &  &  &  &  &  &  \\ 
153 &  &  &  &  &  &  &  \\ 
154 &  &  &  &  &  &  &  \\ 
155 &  &  &  &  &  &  &  \\ 
156 &  &  &  &  &  &  &  \\ 
157 &  &  &  &  &  &  &  \\ 
158 &  &  &  &  &  &  &  \\ 
159 &  &  &  &  &  &  &  \\ 
160 &  &  &  &  &  &  &  \\ 
161 &  &  &  &  &  &  &  \\ 
162 &  &  &  &  &  &  &  \\ 
163 &  &  &  &  &  &  &  \\ 
164 &  &  &  &  &  &  &  \\ 
165 &  &  &  &  &  &  &  \\ 
166 &  &  &  &  &  &  &  \\ 
167 &  &  &  &  &  &  &  \\ 
169 &  &  &  &  &  &  &  \\ 
170 &  &  &  &  &  &  &  \\ 
171 &  &  &  &  &  &  &  \\ 
172 &  &  &  &  &  &  &  \\ 
173 &  &  &  &  &  &  &  \\ 
174 &  &  &  &  &  &  &  \\ 
175 &  &  &  &  &  &  &  \\ 
176 &  &  &  &  &  &  &  \\ 
177 &  &  &  &  &  &  &  \\ 
178 &  &  &  &  &  &  &  \\ 
179 &  &  &  &  &  &  &  \\ 
180 &  &  &  &  &  &  &  \\ 
181 &  &  &  &  &  &  &  \\ 
182 &  &  &  &  &  &  &  \\ 
183 &  &  &  &  &  &  &  \\ 
184 &  &  &  &  &  &  &  \\ 
185 &  &  &  &  &  &  &  \\ 
186 &  &  &  &  &  &  &  \\ 
187 &  &  &  &  &  &  &  \\ 
188 &  &  &  &  &  &  &  \\ 
189 &  &  &  &  &  &  &  \\ 
190 &  &  &  &  &  &  &  \\ 
191 &  &  &  &  &  &  &  \\ 
192 &  &  &  &  &  &  &  \\ 
193 &  &  &  &  &  &  &  \\ 
194 &  &  &  &  &  &  &  \\ 
195 &  &  &  &  &  &  &  \\ 
